

CREATE TABLE CUD_EVENT_LOG_TBL
(
EVENT_ID INT NOT NULL AUTO_INCREMENT, 
EVENT_DATE DATE NOT NULL,
EVENT_TYPE VARCHAR(50), 
EVENT_ACTION VARCHAR(100),
EVENT_DESC VARCHAR(500),
USER_ID VARCHAR(50),
SESSION_ID VARCHAR(100),
IP_ADDRESS VARCHAR(16),
CLIENT_INFO VARCHAR(500),
EVENT_STATUS VARCHAR(2),
OLD_VALUE VARCHAR(4000),
NEW_VALUE VARCHAR(4000),
PRIMARY KEY (EVENT_ID)
);

CREATE TABLE CUD_FD_USER_TMP
(
FD_USER_TMP_ID INT NOT NULL,
FD_USER_MASTER_ID INT, 
FD_USER_NAME  VARCHAR(20), 
FD_USER_FIRST_NAME VARCHAR(30), 
FD_USER_LAST_NAME VARCHAR(30),
CREATED_BY INT,
CREATED_DATE DATE,
MODIFIED_BY INT,
MODIFIED_DATE DATE,
VERIFIED_BY INT,
VERIFIED_DATE DATE,
ACTION_TYPE VARCHAR(3),
REC_STATUS VARCHAR(3),
USER_STATUS VARCHAR(3),
AUTH_COMMENT VARCHAR(300),
PRIMARY KEY (FD_USER_TMP_ID)
);

CREATE TABLE CUD_FD_USER_MASTER
(
FD_USER_MASTER_ID INT NOT NULL,
FD_USER_NAME  VARCHAR(20), 
FD_USER_FIRST_NAME VARCHAR(30), 
FD_USER_LAST_NAME VARCHAR(30),
CREATED_BY INT,
CREATED_DATE DATE,
MODIFIED_BY INT,
MODIFIED_DATE DATE,
VERIFIED_BY INT,
VERIFIED_DATE DATE,
USER_STATUS VARCHAR(3),
PRIMARY KEY (FD_USER_MASTER_ID)
);


CREATE TABLE CUD_COMMON_USER_TMP
(
COMMON_USER_TMP_ID INT NOT NULL,
COMMON_USER_MASTER_ID INT, 
COMMON_USER_ID  VARCHAR(20), 
COMMON_USER_ROLE VARCHAR(30), 
CREATED_BY INT,
CREATED_DATE DATE,
MODIFIED_BY INT,
MODIFIED_DATE DATE,
VERIFIED_BY INT,
VERIFIED_DATE DATE,
ACTION_TYPE VARCHAR(3),
REC_STATUS VARCHAR(3),
USER_STATUS VARCHAR(3),
AUTH_COMMENT VARCHAR(300),
PRIMARY KEY (COMMON_USER_TMP_ID)
);

CREATE TABLE CUD_COMMON_USER_MASTER
(
COMMON_USER_MASTER_ID INT NOT NULL,
COMMON_USER_ID  VARCHAR(20), 
COMMON_USER_ROLE VARCHAR(30),
CREATED_BY INT,
CREATED_DATE DATE,
MODIFIED_BY INT,
MODIFIED_DATE DATE,
VERIFIED_BY INT,
VERIFIED_DATE DATE,
USER_STATUS VARCHAR(3),
PRIMARY KEY (COMMON_USER_MASTER_ID)
);

CREATE TABLE CUD_USER_REFERENCE_TBL
(
REFERENCE_ID INT NOT NULL AUTO_INCREMENT,
USER_ID INT, 
LOGGING_COUNT INT,
FIRST_LOGIN_DATE DATE,
LAST_LOGIN_DATE DATE,
PRIMARY KEY (REFERENCE_ID)
);

CREATE TABLE CUD_COMPANY_USER_TMP
(
COMPANY_USER_TMP_ID INT NOT NULL,
COMPANY_USER_MASTER_ID INT, 
COMPANY_USER_EMP_ID  VARCHAR(30), 
COMPANY_USER_PROF_IMG BLOB, 
COMPANY_USER_FIRST_NAME  VARCHAR(30), 
COMPANY_USER_MIDDLE_NAME VARCHAR(30), 
COMPANY_USER_LAST_NAME VARCHAR(30),
COMPANY_USER_GENDER VARCHAR(3),
COMPANY_USER_GRADE VARCHAR(20),
COMPANY_USER_DESTINATION VARCHAR(30),
COMPANY_USER_DIV_ID VARCHAR(6),
COMPANY_USER_DEP_NAME VARCHAR(50),
COMPANY_USER_FLOOR VARCHAR(3),
COMPANY_USER_JOB_DESC VARCHAR(100),
COMPANY_USER_DEP_EXTEN VARCHAR(6),
COMPANY_USER_OFFICE_MOBILE VARCHAR(15),
COMPANY_USER_OFFICE_EXTEN VARCHAR(6),
COMPANY_USER_OFFICE_EMAIL VARCHAR(30),
COMPANY_USER_CONTACT_PERSON_NAME VARCHAR(50),
COMPANY_USER_CONTACT_PERSON_MOBILE VARCHAR(15),
COMPANY_USER_CONTACT_PERSON_EXTEN VARCHAR(6),
COMPANY_USER_REMARKS VARCHAR(30),
CREATED_BY INT,
CREATED_DATE DATE,
MODIFIED_BY INT,
MODIFIED_DATE DATE,
VERIFIED_BY INT,
VERIFIED_DATE DATE,
ACTION_TYPE VARCHAR(3),
REC_STATUS VARCHAR(3),
USER_STATUS VARCHAR(3),
AUTH_COMMENT VARCHAR(300),
PRIMARY KEY (COMPANY_USER_TMP_ID)
);

CREATE TABLE CUD_COMPANY_USER_MASTER
(
COMPANY_USER_MASTER_ID INT NOT NULL,
COMPANY_USER_EMP_ID  VARCHAR(30), 
COMPANY_USER_PROF_IMG  BLOB, 
COMPANY_USER_FIRST_NAME  VARCHAR(30), 
COMPANY_USER_MIDDLE_NAME VARCHAR(30), 
COMPANY_USER_LAST_NAME VARCHAR(30),
COMPANY_USER_GENDER VARCHAR(3),
COMPANY_USER_GRADE VARCHAR(20),
COMPANY_USER_DESTINATION VARCHAR(30),
COMPANY_USER_DIV_ID VARCHAR(6),
COMPANY_USER_DEP_NAME VARCHAR(50),
COMPANY_USER_FLOOR VARCHAR(3),
COMPANY_USER_JOB_DESC VARCHAR(100),
COMPANY_USER_DEP_EXTEN VARCHAR(6),
COMPANY_USER_OFFICE_MOBILE VARCHAR(15),
COMPANY_USER_OFFICE_EXTEN VARCHAR(6),
COMPANY_USER_OFFICE_EMAIL VARCHAR(30),
COMPANY_USER_CONTACT_PERSON_NAME VARCHAR(50),
COMPANY_USER_CONTACT_PERSON_MOBILE VARCHAR(15),
COMPANY_USER_CONTACT_PERSON_EXTEN VARCHAR(6),
COMPANY_USER_REMARKS VARCHAR(30),
CREATED_BY INT,
CREATED_DATE DATE,
MODIFIED_BY INT,
MODIFIED_DATE DATE,
VERIFIED_BY INT,
VERIFIED_DATE DATE,
USER_STATUS VARCHAR(3),
PRIMARY KEY (COMPANY_USER_MASTER_ID)
);


CREATE TABLE CUD_VISITOR_DATA
(
ID INT NOT NULL AUTO_INCREMENT,
COMPANY_EMP_ID  VARCHAR(20), 
VISITOR_PASS_ID  VARCHAR(20), 
VISITOR_NIC_NUM VARCHAR(20),
CREATED_BY INT,
CREATED_DATE DATE,
PRIMARY KEY (ID)
);


/*
CREATE TABLE CUD_SEQUENCE_NUMBER
(
ID INT NOT NULL,
COMPANY_USER_MASTER_ID INT DEFAULT 0,
COMPANY_USER_TMP_ID INT DEFAULT 0,
FD_USER_MASTER_ID INT DEFAULT 0,
FD_USER_TMP_ID INT DEFAULT 0,
PRIMARY KEY (ID)
);

INSERT INTO 
CUD_USEQUENCE_NUMBER 
(ID,COMPANY_USER_MASTER_ID,COMPANY_USER_TMP_ID,FD_USER_MASTER_ID,FD_USER_TMP_ID) 
VALUES 
(1,0,0,0,0);

COMMIT;
*/

/*----------------------------------------------------------------------------------------------*/
CREATE SCHEMA companydata;
use companydata;
show tables;
DROP DATABASE companydata;
#DROP TABLE company_department;
#DROP TABLE company_user;
#DROP TABLE non_company_user;
commit;

CREATE TABLE NON_COMPANY_USER (
  ID INT NOT NULL AUTO_INCREMENT,
  NON_COMPANY_USER_ID VARCHAR(45) NULL,
  NON_COMPANY_USER_PSWD VARCHAR(45) NULL,
  LOGGIN_FAIL_COUNT INT DEFAULT 0,
  CREATED_BY INT DEFAULT 0,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_BY INT DEFAULT 0,
  MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  VERIFIED_BY INT DEFAULT 0,
  VERIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USER_STATUS VARCHAR(20) NULL,
  PRIMARY KEY (ID)
  );
  
INSERT INTO 
NON_COMPANY_USER (NON_COMPANY_USER_ID,NON_COMPANY_USER_PSWD,USER_STATUS) 
VALUE ("NIMALP","Abc@1234","ACTIVE");

CREATE TABLE COMPANY_USER (
  ID INT NOT NULL AUTO_INCREMENT,
  COMPANY_USER_ID VARCHAR(45) NULL,
  COMPANY_USER_PSWD VARCHAR(45) NULL,
  COMPANY_USER_FIRST_NAME VARCHAR(45) NULL,
  COMPANY_USER_LAST_NAME VARCHAR(45) NULL,
  COMPANY_USER_DEP_ID VARCHAR(45) NULL,
  COMPANY_USER_DEP_NAME VARCHAR(45) NULL,  
  CREATED_BY INT DEFAULT 0,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_BY INT DEFAULT 0,
  MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  VERIFIED_BY INT DEFAULT 0,
  VERIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USER_STATUS VARCHAR(20) NULL,
  USER_ROLE INT DEFAULT 0,
  PRIMARY KEY (`ID`)
  );


INSERT INTO COMPANY_USER (COMPANY_USER_ID,COMPANY_USER_PSWD,COMPANY_USER_FIRST_NAME,COMPANY_USER_LAST_NAME,COMPANY_USER_DEP_ID,COMPANY_USER_DEP_NAME,USER_STATUS) 
VALUE ("LAHIRUP","Abc@1234","LAHIRU","PRIYANKARA","001","IT","ACTIVE");

INSERT INTO COMPANY_USER (COMPANY_USER_ID,COMPANY_USER_PSWD,COMPANY_USER_FIRST_NAME,COMPANY_USER_LAST_NAME,COMPANY_USER_DEP_ID,COMPANY_USER_DEP_NAME,USER_STATUS) 
VALUE 
("TEST_USER1","Abc@1234","TU1_F_NAME","TU1_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER2","Abc@1234","TU2_F_NAME","TU2_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER3","Abc@1234","TU3_F_NAME","TU3_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER4","Abc@1234","TU4_F_NAME","TU4_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER5","Abc@1234","TU5_F_NAME","TU5_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER6","Abc@1234","TU6_F_NAME","TU6_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER7","Abc@1234","TU7_F_NAME","TU7_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER8","Abc@1234","TU8_F_NAME","TU8_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER9","Abc@1234","TU9_F_NAME","TU9_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER10","Abc@1234","TU10_F_NAME","TU10_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER11","Abc@1234","TU11_F_NAME","TU11_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER12","Abc@1234","TU12_F_NAME","TU12_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER13","Abc@1234","TU13_F_NAME","TU13_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER14","Abc@1234","TU14_F_NAME","TU14_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER15","Abc@1234","TU15_F_NAME","TU15_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER16","Abc@1234","TU16_F_NAME","TU16_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER17","Abc@1234","TU17_F_NAME","TU17_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER18","Abc@1234","TU18_F_NAME","TU18_L_NAME","920","IT Department","ACTIVE"),
("TEST_USER19","Abc@1234","TU19_F_NAME","TU19_L_NAME","921","Audit Department","ACTIVE"),
("TEST_USER20","Abc@1234","TU20_F_NAME","TU20_L_NAME","921","Audit Department","ACTIVE"),
("TEST_USER21","Abc@1234","TU21_F_NAME","TU21_L_NAME","921","Audit Department","ACTIVE"),
("TEST_USER22","Abc@1234","TU22_F_NAME","TU22_L_NAME","921","Audit Department","ACTIVE"),
("TEST_USER23","Abc@1234","TU23_F_NAME","TU23_L_NAME","921","Audit Department","ACTIVE"),
("TEST_USER24","Abc@1234","TU24_F_NAME","TU24_L_NAME","921","Audit Department","ACTIVE"),
("TEST_USER25","Abc@1234","TU25_F_NAME","TU25_L_NAME","921","Audit Department","ACTIVE"),
("TEST_USER26","Abc@1234","TU26_F_NAME","TU26_L_NAME","921","Audit Department","ACTIVE"),
("TEST_USER27","Abc@1234","TU27_F_NAME","TU27_L_NAME","921","Audit Department","ACTIVE"),
("TEST_USER28","Abc@1234","TU28_F_NAME","TU28_L_NAME","921","Audit Department","ACTIVE"),
("TEST_USER29","Abc@1234","TU29_F_NAME","TU29_L_NAME","921","Audit Department","ACTIVE"),
("TEST_USER30","Abc@1234","TU30_F_NAME","TU30_L_NAME","921","Audit Department","ACTIVE"),
("TEST_USER31","Abc@1234","TU31_F_NAME","TU31_L_NAME","921","Audit Department","ACTIVE"),
("TEST_USER32","Abc@1234","TU32_F_NAME","TU32_L_NAME","922","HR Department","ACTIVE"),
("TEST_USER33","Abc@1234","TU33_F_NAME","TU33_L_NAME","922","HR Department","ACTIVE"),
("TEST_USER34","Abc@1234","TU34_F_NAME","TU34_L_NAME","922","HR Department","ACTIVE"),
("TEST_USER35","Abc@1234","TU35_F_NAME","TU35_L_NAME","922","HR Department","ACTIVE"),
("TEST_USER36","Abc@1234","TU36_F_NAME","TU36_L_NAME","922","HR Department","ACTIVE"),
("TEST_USER37","Abc@1234","TU37_F_NAME","TU37_L_NAME","922","HR Department","ACTIVE"),
("TEST_USER38","Abc@1234","TU38_F_NAME","TU38_L_NAME","922","HR Department","ACTIVE"),
("TEST_USER39","Abc@1234","TU39_F_NAME","TU39_L_NAME","922","HR Department","ACTIVE"),
("TEST_USER40","Abc@1234","TU40_F_NAME","TU40_L_NAME","922","HR Department","ACTIVE"),
("TEST_USER41","Abc@1234","TU41_F_NAME","TU41_L_NAME","922","HR Department","ACTIVE"),
("TEST_USER42","Abc@1234","TU42_F_NAME","TU42_L_NAME","922","HR Department","ACTIVE")
;

INSERT INTO COMPANY_USER (COMPANY_USER_ID,COMPANY_USER_PSWD,COMPANY_USER_FIRST_NAME,COMPANY_USER_LAST_NAME,COMPANY_USER_DEP_ID,COMPANY_USER_DEP_NAME,USER_STATUS,USER_ROLE) 
VALUE 
("NIMALP","Abc@1234","NIMAL","PERERA","920","IT Department","ACTIVE",1),
("SANDUNM","Abc@1234","SANDUN","MADHUSANKA","920","IT Department","ACTIVE",2),
("KELUMA","Abc@1234","KELIM","ADIKARI","920","IT Department","ACTIVE",3),
("SUNETHT","Abc@1234","SUNETH","THILAKARATHNE","920","IT Department","ACTIVE",4),
("MADHURAH","Abc@1234","MADHRA","HEWAGE","921","Audit Department","ACTIVE",3),
("NIROSHANS","Abc@1234","NIROSHAN","SANDAKELUM","921","Audit Department","ACTIVE",4),
("SANUNIM","Abc@1234","SANDUNI","MADHUSHIKA","922","HR Department","ACTIVE",3),
("MENAKAJ","Abc@1234","MENAKA","JAYARANGA","922","HR Department","ACTIVE",4)
;


CREATE TABLE COMPANY_DEP_INFO (
  ID INT NOT NULL AUTO_INCREMENT,
  BRANCH_ID VARCHAR(45) NULL,
  DEPARTMENT_ID VARCHAR(45) NULL,
  DEPARTMENT_NAME VARCHAR(45) NULL,
  CREATED_BY INT  DEFAULT 0,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_BY INT DEFAULT 0,
  MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  VERIFIED_BY INT DEFAULT 0,
  VERIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DEPARTMENT_STATUS VARCHAR(20) NULL,
  PRIMARY KEY (ID)
  );
  
  
  
INSERT INTO COMPANY_DEP_INFO
(BRANCH_ID,DEPARTMENT_ID,DEPARTMENT_NAME,DEPARTMENT_STATUS) 
VALUE 
("001","92","Trade Services1","ACTIVE"),
("001","93","Trade Services2","ACTIVE");

INSERT INTO COMPANY_DEP_INFO
(BRANCH_ID,DEPARTMENT_ID,DEPARTMENT_NAME,DEPARTMENT_STATUS) 
VALUE 
("001","920","IT Department","ACTIVE"),
("001","921","Audit Department","ACTIVE"),
("001","922","HR Department","ACTIVE"),
("001","923","Finance Department.","ACTIVE"),
("001","924","Operations Department","ACTIVE"),
("001","925","Trade Services Department","ACTIVE"),
("001","928","Risk Management Department","ACTIVE"),
("001","929","EDP Department","ACTIVE"),
("001","930","Planning Department","ACTIVE");

commit;
  